[build]
  base = "client/landing_newTime"
  command = "npm run build"
  publish = "client/landing_newTime/dist"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200